#pragma once

#include "emitters/screensaver_kind_emitter.hpp"
#include "emitters/action_kind_emitter.hpp"
#include "emitters/color_emitter.hpp"
#include "emitters/game_kind_emitter.hpp"
#include "emitters/application_mode_emitter.hpp"
#include "emitters/aspect_ratio_emitter.hpp"
#include "emitters/size_emitter.hpp"
#include "emitters/manager_emitter.hpp"
#include "emitters/data_emitter.hpp"
#include "emitters/field_emitter.hpp"
#include "emitters/object_emitter.hpp"
#include "emitters/object_kind_emitter.hpp"
#include "emitters/view_emitter.hpp"
#include "emitters/shape_emitter.hpp"
#include "emitters/point_emitter.hpp"
