padding: 0

proportional: true
smooth_zooming: true
multisample: true

grid_type: square
screensaver: no

full_screen: true
game_mode: false

foreword: false
afterword: true
window_width: 960
window_height: 540

shape: diamond
animation: fade
selection_color: soft_green

foreword_timeout: 5
menu_timeout: 30
screensaver_timeout: 30
afterword_timeout: 3

images_directory: "../images/pictures/"
#fonts_directory: "fonts/"
font_name: "mono-55"
