padding: 0.1
afterword_timeout: 5
window_width: 960
proportional: true
screensaver_timeout: 30
game_mode: false
window_height: 540
full_screen: false
selection_color:
  - 0
  - 0
  - 255
afterword: true
foreword: true
font_name: mono-55
smooth_zooming: true
images_directory: images/
levels_directory: levels/
menu_timeout: 30
multisample: false
fonts_directory: fonts/
foreword_timeout: 5