fonts_directory: fonts/
smooth_zooming: true
screensaver_kind: ~
window_height: 540
proportional: true
aspect_ratio:
  - 16
  - 9
clear_color:
  - 255
  - 255
  - 255
levels_directory: levels/
multisample: false
window_width: 960
padding: 0.1
game_mode: false
full_screen: false
selection_color:
  - 0
  - 0
  - 255
afterword: true
foreword_timeout: 5
images_directory: images/
foreword: true
afterword_timeout: 5
screensaver_timeout: 30
font_name: mono-55
menu_timeout: 30