game_mode: false
padding: 5
selection_color:
  - 0
  - 0
  - 255
clear_color:
  - 255
  - 255
  - 255
foreword: true
afterword: true
images_directory: images/
font_name: mono-55
fonts_directory: fonts/
screensaver_kind: ~
levels_directory: levels/
foreword_timeout: 5
menu_timeout: 30
screensaver_timeout: 30
afterword_timeout: 5
proportional: true
full_screen: true
smooth_zooming: true
multisample: true
window_width: 1366
aspect_ratio:
  - 16
  - 9
window_height: 767