padding: 0.1

proportional: true
smooth_zooming: true
multisample: true

grid_type: square
screensaver: no

full_screen: true
game_mode: false

foreword: on
afterword: on
window_width: 960
window_height: 540

default_shape: square
animation: fade
selection_color: soft_blue
shape: rectangle

foreword_timeout: 5
menu_timeout: 30
screensaver_timeout: 30
afterword_timeout: 3

images_directory: "../images/pictures/"
