smooth_zooming: true
multisample: true
window_width: 1366
window_height: 767
aspect_ratio:
  - 16
  - 9
full_screen: true
game_mode: false
padding: 1
selection_color:
  - 0
  - 0
  - 255
clear_color:
  - 255
  - 255
  - 255
foreword: false
afterword: false
images_directory: images/
font_name: mono-55
fonts_directory: fonts/
screensaver_kind:
  - queens
levels_directory: levels/
foreword_timeout: 5
menu_timeout: 30
screensaver_timeout: 30
afterword_timeout: 5
proportional: true