screensaver: 60 # (on | timeout)
greeting: on # (on | off)
credits: on # (on | off)
format: 4x3 # (4x3 | 16x9 | auto)
fullscreen: on # (on | off)
# autosave this options
#position: [0, 0] # initial position
#size: [800, 600] # size

#adjust: off # (on | off)

