game:
  sleep: 1000

colors:
  # default: all # or just redefine them
  fantazy: [255, 200, 200]

fields:
  f:
    size: [10, 10]
    data:
      a: [1, 1]

views:
  v:
    field: f

object_kinds:
  A:
    color: fantazy

objects:
  A:
    a

controls:
  w:
    object: s
    action: move
    option: [0, 1]
  a:
    object: s
    action: move
    option: [-1, 0]
  s:
    object: s
    action: move
    option: [0, -1]
  d:
    object: s
    action: move
    option: [1, 0]

#timer:
