game:
  kind: sokoban
  screen: [10, 10]

colors:
  sky: [0, 156, 255]
  viol: [219, 103, 217]

fields:
  field:
    size: [10, 10]
    data:
      s: [1, 1]
      1: [1, 5]
      2: [6, 7]
      3: [5, 3]

views:
  view:
    field: field

object_kinds:
  sokoban:
    color: sky
    shape: star
  box:
    color: viol

interactions:
  sokoban:
    push: box

objects:
  sokoban: s
  box: [1, 2, 3]

controls:
  w: &up
    object: s
    action: move
    option: [0, 1]
  a: &left
    object: s
    action: move
    option: [-1, 0]
  s: &down
    object: s
    action: move
    option: [0, -1]
  d: &right
    object: s
    action: move
    option: [1, 0]
  ö: &up
  ô: &left
  û: &down
  â: &right

