object_kinds:
  light_box:
    color: green
  heavy_box:
    color: blue
  sokoban:
    color: violet
    shape: star

interactions:
  sokoban: # object kind
    push: # interactions
      - light_box
      - heavy_box
  heavy_box:
    push: light_box # scalar or sequense

objects:
  light_box:
    - box_1
    - box_2
  heavy_box:
    - box_3
  sokoban:
    - sokoban_1
    - sokoban_2

fields:
  field:
    size:
      width: 10
      height: 10
    closure: full
    data:
      sokoban: # object name
        column: 1
        row: 1
      box_1: # you may use mapping with 'column' and 'row' keys ...
        column: 5
        row: 5
      box_2: # ... or 2 element sequense
        - 6
        - 5
      box_3: [4, 3] # it can be written as a comma separated list within square brackets
  info:
    size: 5

views:
  view:
    field: field
    size: [12, 12]
    offset:
      column: -1
      row: -1
    position:
      column: 5
      row: 5

controls:
  w: # list of objects
    sokoban: # list of actions with this object
      move: [1, 1]
  a:
    sokoban:
      move: [1, 1]
  s:
    sokoban:
      move: [1, 1]
  d:
    sokoban:
      move: [1, 1]
  # or more even complex
  #e:
  #  actions:
  #    move:
  #  targets:
  #    objects:
  #    objects_kinds:
