game:
  sleep: 1000

colors:
  sky: [0, 156, 255]

fields:
  f:
    size: [10, 10]
    data:
      a: [1, 1]

views:
  v:
    field: f

object_kinds:
  A:
    color: sky

objects:
  A:
    a

controls:
  w:
    object: a
    action: move
    option: [0, 1]
  a:
    object: a
    action: move
    option: [-1, 0]
  s:
    object: a
    action: move
    option: [0, -1]
  d:
    object: a
    action: move
    option: [1, 0]

timer:
  object: s
  action: move
