game:
  difficulty: 1
  screen: [7, 7]

#shapes:
#  diamond: diamond
#  circle: circle

kinds:
  sokoban:
    color: purple
    shape: diamond
    mask: [[0, 0]]
  box:
    color: green
  destination: null
  wall: null

interactions:
  sokoban: # object kind
    push: # interactions
      - box

fields:
  field:
    size: [5, 5]
    objects:
      sokoban: [['sokoban_1', 0, 4]]
      wall: [[0, 3], [1, 3], [2, 3]]
      box: [[2, 2]]
    cells: [[2, 1]]
    #cells:
    #  destination: [2, 1]

views:
  view:
    field: field
    border_color: green
    grid_color: black
    offset: [0, 0]
    position: [1, 1]
    direction: [1, 1]
    cells_color: red

units:
  player_1: sokoban_1
