game:
  difficulty: 1
  screen: [7, 7]

colors:
  sky_blue: sky-blue
  blue: blue
  sea_green: sea-green
  black: black

shapes:
  diamond: diamond
  star7: [ngon, 7, 3]

kinds:
  sokoban:
    color: purple
    shape: circle
  box:
    color: green
  destination: null
  wall: null

fields:
  field:
    size: [5, 5]
    objects:
      sokoban: [1, 5]
      wall: [[1, 4], [2, 4], [3, 4]]
      box: [3, 3]
    cells:
      destination: [3, 2]

views:
  view:
    field: field
    background_color: blue
    field_color: sky_blue
    cells_color: blue
    grid_color: black
    offset: [0, 0]
    position: [1, 1]
    direction: [1, 1]

controls:
  sokoban: first_player # look up for first sokoban or for all sokobans
