game:
  kind: sokoban
  screen: [10, 10]

fields:
  field:
    size: [10, 10]
    data:
      s: [1, 1]
      1: [1, 5]
      2: [6, 7]
      3: [5, 3]

colors:
  dark_blue: [32, 74, 735]
  sky: [50, 180, 255]

views:
  view:
    field: field
    background_color: sky
    cells_color: soft_blue

object_kinds:
  sokoban:
    color: dark_blue
    shape: diamond
  box:
    color: dark_blue

interactions:
  sokoban:
    push: box

objects:
  sokoban: s
  box: [1, 2, 3]

controls:
  w: &up
    object: s
    action: move
    option: [0, 1]
  a: &left
    object: s
    action: move
    option: [-1, 0]
  s: &down
    object: s
    action: move
    option: [0, -1]
  d: &right
    object: s
    action: move
    option: [1, 0]
