game:
  difficulty: 1
  screen: [7, 7]

interactions:
  sokoban: # object kind
    push: # interactions
      - box

colors:
  light-green: [hsv, 120.0, 0.1, 1]

kinds:
  sokoban:
    color: purple
    shape: diamond
    #mask: [[0, 0], [1, 0]]
  box:
    color: green
  destination: null
  wall: null

fields:
  field:
    size: [5, 5]
    objects:
      sokoban: [['sokoban_1', 0, 4]]
      wall: [[0, 3], [1, 3], [2, 3]]
      box: [[2, 2]]
    cells: [[2, 1]]
    #cells:
    #  destination: [2, 1]

views:
  view:
    field: field
    border_color: purple
    grid_color: black
    offset: [0, 0]
    position: [1, 1]
    direction: [1, 1]
    cells_color: light-green

units:
  player_1: sokoban_1
