game:
  kind: sokoban
  screen: [12, 12]

fields:
  field:
    size: [10, 10]
    data:
      s: [1, 1]
      1: [1, 5]
      2: [6, 7]
      3: [5, 3]
    cells: [[5, 5], [6, 5], [7, 5]]

colors:
  seven: [7, 7, 7]

views:
  view:
    field: field
    background_color: blue
    field_color: sky-blue
    cells_color: blue
    position: [1, 1]

object_kinds:
  sokoban:
    color: purple
    shape: david
  box:
    color: green

objects:
  sokoban: s
  box: [1, 2, 3]

controls:
  first_player: s
