game:
  difficulty: 1
  screen: [7, 7]

shapes:
  diamond: diamond
  circle: circle
  star7: [ngon, 7, 3]

kinds:
  sokoban:
    color: purple
    shape: diamond
    mask: [[0, 0]]
  box:
    color: green
  destination: null
  wall: null

fields:
  field:
    size: [5, 5]
    objects:
      sokoban: [['sokoban_1', 0, 4]]
      wall: [[0, 3], [1, 3], [4, 3],
             [0, 0], [3, 1], [4, 1]]
      box: [[1, 2]]
    cells:
      destination: [2, 1]

views:
  view:
    field: field
    #size: [5, 5]
    #background_color: soft-blue
    #field_color: sky-blue
    #cells_color: blue
    border_color: green
    grid_color: black
    offset: [0, 0]
    position: [1, 1]
    direction: [1, 1]

units:
  player_1: sokoban_1
