game:
  difficulty: 1
  screen: [8, 8]

interactions:
  sokoban: # object kind
    push: # interactions
      - rbox
      - gbox

colors:
  light-green: [hsv, 120.0, 0.1, 1]
  light-red: [hsv, 0.0, 0.1, 1]

shapes:
  diamond: diamond
  circle: circle
  star7: [ngon, 7, 3]

kinds:
  sokoban:
    color: purple
    shape: diamond
    mask: [[0, 0]]
  gbox:
    color: green
  rbox:
    color: red
  #destination: null
  destination:
    color: light-green
  wall: null

fields:
  field:
    size: [6, 6]
    objects:
      sokoban: [['sokoban_1', 1, 0]]
      wall: [
        [0, 5], [1, 5], [5, 5],
        [3, 4], [5, 4],
        [1, 3],
        [4, 2],
        [0, 1], [2, 1],
        [0, 0], [4, 0], [5, 0]
      ]
      gbox: [[2, 4]]
      rbox: [[1, 2]]
    cells: [
      [3, 1], [4, 3]
    ]
    #cells:
    #  destination: [2, 1]

views:
  view:
    field: field
    cells_color: light-red
    border_color: purple
    grid_color: black
    offset: [0, 0]
    position: [1, 1]
    direction: [1, 1]

units:
  player_1: sokoban_1
