game:
  difficulty: 1
  screen: [8, 8]

interactions:
  sokoban: # object kind
    push: # interactions
      - gbox
      - cbox
      - obox

colors:
  light-green: [hsv, 120.0, 0.1, 1]
  light-red: [hsv, 0.0, 0.1, 1]

shapes:
  diamond: diamond
  circle: circle
  star7: [ngon, 7, 3]

kinds:
  sokoban:
    color: purple
    shape: diamond
    mask: [[0, 0]]

  gbox:
    color: green
  cbox:
    color: cyan
  obox:
    color: orange

  gcell:
    color: light-green
  ccell:
    color: light-cyan
  ocell:
    color: light-orange
  scell:
    color: light-purple

  wall: null

fields:
  field:
    size: [6, 6]
    objects:
      sokoban: [['sokoban_1', 3, 1]]
      wall: [
        [0, 5], [1, 5], [5, 5],
        [3, 4], [5, 4],
        [1, 3],
        [4, 2],
        [0, 1], [2, 1],
        [0, 0], [4, 0], [5, 0]
      ]
      gbox: [[1, 2]]
      cbox: [[2, 4]]
      obox: [[4, 3]]
    cells: [
      [1, 2], [2, 4], [4, 3], [3, 1]
    ]
    #cells:
    #  gcell: [[3, 1]]
    #  rcell: [[4, 3]]

views:
  view:
    field: field
    cells_color: light-red
    border_color: purple
    grid_color: black
    offset: [0, 0]
    position: [1, 1]
    direction: [1, 1]

units:
  player_1: sokoban_1
