grid_type: Square
screensaver: [Random]
full_screen: on
game_mode: off
foreword: on
afterword: on
window_width: 960
window_height: 540

shape: rectangle
animation: fade
color: blue
shape: rectangle

foreword_timeout: 5
menu_timeout: 5
screensaver_timeout: 5
afterword_timeout: 5
