proportional: on
smooth_zooming: on
multisample: off

grid_type: Square
screensaver: No
full_screen: on
game_mode: off

foreword: off
afterword: off
window_width: 960
window_height: 540

shape: rectangle
animation: fade
selection_color: SOFT_BLUE
shape: rectangle

foreword_timeout: 5
menu_timeout: 3
screensaver_timeout: 30
afterword_timeout: 5

