proportional: on
smooth_zooming: on
multisample: off

grid_type: Square
screensaver: No
full_screen: off
game_mode: off

foreword: on
afterword: on
window_width: 960
window_height: 540

shape: rectangle
animation: fade
selection_color: VIOLET
shape: rectangle

foreword_timeout: 5
menu_timeout: 30
screensaver_timeout: 30
afterword_timeout: 3

